version: '3'

services:
  scrappy:
    image: docker.pkg.github.com/vaultvulp/lost-proxy/lost-proxy-app:latest
    restart: unless-stopped
    volumes:
    - webroot:/app/src/webroot
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"

  caddy:
    image: docker.pkg.github.com/vaultvulp/lost-proxy/lost-proxy-caddy:latest
    restart: unless-stopped
    ports: 
    - "80:80"
    - "443:443"
    - "2015:2015"
    volumes:
    - webroot:/srv:ro
    logging:
      driver: json-file
      options:
          max-size: "10m"
          max-file: "5"

volumes:
  webroot:
