name: Build

# on:
#   push:
#     branches:
#       - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build app
      run: |
         docker build -t docker.pkg.github.com/${{ github.repository }}/app:latest ./app
    
    - name: Build caddy
      run: |
         docker build -t docker.pkg.github.com/${{ github.repository }}/caddy:latest ./caddy