name: Build

on:
  push:
    branches:
      - master
      - feature/setup-actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build app
      run: |
        docker build -t docker.pkg.github.com/${github.repository,,}/app:latest ./app
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build caddy
      run: |
        docker build -t docker.pkg.github.com/${github.repository,,}/caddy:latest ./caddy
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Authenticate to GitHub Package Registry
      run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_TOKEN}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}