name: Build and Publish

on:
  push:
    branches:
      - master
      - feature/setup-actions

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build app
      run: |
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY,,}/lost-proxy-app:latest ./app
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Build caddy
      run: |
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY,,}/lost-proxy-caddy:latest ./caddy
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    
    - name: Authenticate to GitHub Package Registry
      run: docker login docker.pkg.github.com -u publisher -p "${{ secrets.github_token }}"

    - name: Publish images
      run: |
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/lost-proxy-app:latest
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/lost-proxy-caddy:latest
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    